FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /server .

FROM alpine:latest
COPY --from=build /server /usr/local/bin/server
EXPOSE 8081
CMD ["server"]
